### ISSUE TITLE
minor improvements

### ISSUE THREAD

**Issue by mrose17** [brave/ledger-publisher#13]
1. if there is an error in `require('./categories').all()`, invoke the callback with `null`
2. figure out an easy way to generate `var rules` in `index.js`, perhaps by having it do a `require(...)` on a file that is generated on commit

**Comment by aekeus** [comment]
The callback currently takes two parameters, the first is the err object and the second is the array of rules. Would you like the array of rules parameter to be null when an error occurs?

**Comment by mrose17** [comment]
i thought there was only one parameter. in that case: when an error occurs, please use `(err, null)`  thanks!
