### ISSUE TITLE
candidates for publisher exclusion

### ISSUE THREAD

**Issue by mrose17** [brave/ledger-publisher#19]
brave.com, you guys 
flattr.net, micropayment service 
fastmail.com, email and calendar service provider 
ixquick.com, search engine powered by Google 
dogpile.com, metasearch engine 
kvasir.no, search engine powered by Google 
hvaerminip.no, IP address discovery service 
ipv6-test.com, network testing utility 
test-ipv6.com, network testing utility 
searx.me, meta search engine 
steampowered.com, game distributor 
yr.no, weather forecast 
storytel.no, audiobook marketplace 
audible.com, audiobook marketplace 
icloud.com, personal information services provider 
simplenote.com, note taking service 
openhub.net, open-source contributions tracker

cc: @Aeyoun

**Comment by mrose17** [comment]
@Aeyoun - we don't have a full set of rules yet as to what should constitute a publisher.

one suggestion was to see if we blocked any ads on the site, and if so, then that would make it a publisher. the issue with that is that some sites would benefit from contributions, but don't do ads today.

for my own browser settings, the rule i use is "if i send them money, they don't get contributions, otherwise, fine."

what's your thinking?

thanks,

/mtr
cc: @aekeus

**Comment by da2x** [comment]
I’ve removed hundreds of websites from my ledger over the course of a month. It’s too much work to maintain the ledger at the moment. Can I send you my current ledger with statuses? Or does Brave collect the websites I toggle off and remove the ones that thousands of users have toggled off? … To let users vote on it but let individual users override it locally.

I had some 600 entries on my ledger and toggled off 400 of them. God damned reCAPTCHA was at the top of my list last month.

**Comment by mrose17** [comment]
sorry for the delay in replying, for some reason, your comment didn't result in a ping to me.

first things first: your browsing history and publisher synopsis is kept on your browser and never sent to any servers.

over the last few months, there have been several internal discussions as to how publishers should be identified. the present strategy is to use a curated ruleset that excludes the most common non-publisher sites.  

one suggestion was to change the default case from "it's a publisher" to "if the browser blocked at least one add from the page, then it's a puboisher".

comments?

ps: what i don't understand in your report is that things like captcha's are embedded in a webpage, and those are never evaluated for publisher status. so i'm wondering how that shows up at all.

thanks,

/mtr

**Comment by da2x** [comment]
> one suggestion was to change the default case from "it's a publisher" to "if the browser blocked at least one add from the page, then it's a puboisher". 

Hm. I kind of like funding websites that don’t rely on ads. Open source projects will probably appreciate a payment from Brave customers even though they don’t all put up ads on their websites. It sure is a complicated problem you guys have created for yourself. Making all or even the majority of users will be very tricky indeed.

The list of websites I’ve excluded is very varied. I’ve excluded stores, commercial service providers, some web tools but not all, websites that I pay for in other ways, websites that don’t provide any "infotainment" or news content, and a whole bunch of other websites.

Maybe fix it by making it easier to disable sites? Why isn’t a ledger toggle included in the Bravery-menu, for example? Or add a money faucet icon somewhere more prominently in the UI where users can disable websites they don’t want to fund.

**Comment by mrose17** [comment]
list above fixed by https://github.com/brave/ledger-publisher/pull/20
